- rest:
    post:
    - id: "create-customer"
      path: "/customer"
      consumes: "application/json"
      produces: "application/json"
      param:
      - dataType: "string"
        defaultValue: ""
        description: ""
        name: "body"
        required: true
        type: "body"
      to: "direct:create-customer"
